matriz = [[],[],[],[],[],[],[],[],[]]
matriz[0].append(int(input('número da posição [0,0]: ')))
matriz[1].append(int(input('número da posição [0,1]: ')))
matriz[2].append(int(input('número da posição [0,2]: ')))
matriz[3].append(int(input('número da posição [1,0]: ')))
matriz[4].append(int(input('número da posição [1,1]: ')))
matriz[5].append(int(input('número da posição [1,2]: ')))
matriz[6].append(int(input('número da posição [2,0]: ')))
matriz[7].append(int(input('número da posição [2,1]: ')))
matriz[8].append(int(input('número da posição [2,2]: ')))
print('='*30)
print(matriz[0],end='')
print(matriz[1],end='')
print(matriz[2])
print(matriz[3],end='')
print(matriz[4],end='')
print(matriz[5])
print(matriz[6],end='')
print(matriz[7],end='')
print(matriz[8])

